# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cansanidevelopment
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: first-serverless
# "service" is the name of this project. This will also be added to your AWS resource names.
service: first-serverless

plugins:
  - serverless-offline
  - serverless-s3-local

useDotenv: true

params:
  default:
    jwtSecret: ${env:JWT_SECRET}
    bucketName: ${env:BUCKET_NAME}

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    JWT_SECRET: ${param:jwtSecret}
    BUCKET_NAME: ${param:bucketName}

functions:
  createUser:
    handler: src/controllers/users/create/index.handler
    events:
      - httpApi:
          path: /users
          method: post

  getUserById:
    handler: src/controllers/users/get-user/index.handler
    events:
      - httpApi:
          path: /users/{id}
          method: get

  getUsers:
    handler: src/controllers/users/get-all-users/index.handler
    events:
      - httpApi:
          path: /users
          method: get

  updateUser:
    handler: src/controllers/users/update/index.handler
    events:
      - httpApi:
          path: /users/{id}
          method: patch

  deleteUser:
    handler: src/controllers/users/delete/index.handler
    events:
      - httpApi:
          path: /users/{id}
          method: delete

  signIn:
    handler: src/controllers/authenticate/sign-in/index.handler
    events:
      - httpApi:
          path: /sessions
          method: post

  getAuthenticatedUser:
    handler: src/controllers/authenticate/get-authenticated-user.ts/index.handler
    events:
      - httpApi:
          path: /me
          method: get

  uploadUsers:
    handler: src/controllers/batch/upload/index.handler
    events:
      - httpApi:
          path: /users/upload
          method: post

  createUsersInBatch:
    handler: src/controllers/batch/create/index.handler
    events:
      - s3:
          bucket: ${param:bucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json
            - suffix: .csv
